-- ============================================================================
-- HEBAS - 01_schema.sql
-- Consolidated, de-duplicated, dependency-ordered DDL.
-- Source of truth: dbs_theory_database.txt (design reference).
-- Fixes applied vs. reference:
--   * Single Nurses definition (reference declared it twice).
--   * Equipment_Type folded into Sanitization_Logs (reference ALTERed twice).
--   * Primary_Diagnosis / Diagnosis_Timestamp inlined into Admissions.
--   * Arrival_Queue.CNIC widened 5 -> 15.
--   * Patient_Profile.User_ID added (optional patient login link).
--   * Triggers/procs/views live in 03_programmable.sql (created after seed).
-- No statement terminators other than ';' in this file (no PL/SQL here).
-- ============================================================================

-- 1. USERS (superclass)
CREATE TABLE HEBAS_Users (
    UserID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FName          VARCHAR2(50) NOT NULL,
    LName          VARCHAR2(50) NOT NULL,
    Email          VARCHAR2(100) UNIQUE NOT NULL,
    Password_Hash  VARCHAR2(255) NOT NULL,
    Phone          VARCHAR2(15),
    Is_Active      NUMBER(1) DEFAULT 1 CHECK (Is_Active IN (0, 1))
);

-- 2. RBAC role catalogue + assignment (authoritative role lookup for login)
CREATE TABLE User_Roles (
    Role_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Role_Name  VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE User_Role_Assignment (
    UserID   NUMBER NOT NULL,
    Role_ID  NUMBER NOT NULL,
    PRIMARY KEY (UserID, Role_ID),
    CONSTRAINT fk_ura_user FOREIGN KEY (UserID) REFERENCES HEBAS_Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_ura_role FOREIGN KEY (Role_ID) REFERENCES User_Roles(Role_ID)
);

-- 3. WARDS (superclass)
CREATE TABLE Wards (
    Ward_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Floor_Number      NUMBER NOT NULL,
    Ward_Type         VARCHAR2(20) CHECK (Ward_Type IN ('EMERGENCY', 'RECOVERY')),
    Total_Capacity    NUMBER NOT NULL,
    Current_Capacity  NUMBER DEFAULT 0
);

-- 4. EQUIPMENT (superclass)
CREATE TABLE Equipment (
    Equipment_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Equipment_Name  VARCHAR2(100) NOT NULL,
    Equipment_Type  VARCHAR2(50),
    Size_Area       VARCHAR2(50),
    Status          VARCHAR2(20) CHECK (Status IN ('FUNCTIONAL', 'MAINTENANCE', 'BROKEN'))
);

-- 5. BEDS (superclass)
CREATE TABLE Beds (
    Bed_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Bed_Number      VARCHAR2(10) UNIQUE NOT NULL,
    Bed_Type        VARCHAR2(30),
    Bed_Size        VARCHAR2(20),
    Current_Status  VARCHAR2(20) DEFAULT 'AVAILABLE'
                    CHECK (Current_Status IN ('AVAILABLE', 'OCCUPIED', 'PENDING_CLEANING'))
);

-- 6. PATIENT PROFILE (static demographic data; optional login link via User_ID)
CREATE TABLE Patient_Profile (
    Patient_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_ID            NUMBER,
    Full_Name          VARCHAR2(100) NOT NULL,
    Date_of_Birth      DATE NOT NULL,
    Gender             VARCHAR2(10) CHECK (Gender IN ('M', 'F', 'OTHER')),
    National_ID        VARCHAR2(20) UNIQUE NOT NULL,
    Insurance_ID       VARCHAR2(50),
    Emergency_Contact  VARCHAR2(15),
    CONSTRAINT fk_patient_user FOREIGN KEY (User_ID) REFERENCES HEBAS_Users(UserID)
);

-- 7. STAFF SUBCLASSES (PK == HEBAS_Users.UserID)
CREATE TABLE Doctor_Profiles (
    Doctor_ID       NUMBER PRIMARY KEY,
    Specialization  VARCHAR2(50),
    License_No      VARCHAR2(50) UNIQUE NOT NULL,
    Department      VARCHAR2(50),
    Shift_Timing    VARCHAR2(20),
    CONSTRAINT fk_doc_user FOREIGN KEY (Doctor_ID) REFERENCES HEBAS_Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Admin_Staff (
    Admin_ID         NUMBER PRIMARY KEY,
    Department       VARCHAR2(50),
    Seniority_Level  VARCHAR2(20),
    Access_Level     VARCHAR2(20),
    Duty_Timing      VARCHAR2(20),
    City             VARCHAR2(50),
    Street           VARCHAR2(100),
    House_No         VARCHAR2(20),
    CONSTRAINT fk_admin_user FOREIGN KEY (Admin_ID) REFERENCES HEBAS_Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Maintenance_Staff (
    Maintenance_ID  NUMBER PRIMARY KEY,
    Shift_Timing    VARCHAR2(20),
    Assigned_Ward   NUMBER,
    CONSTRAINT fk_maint_user FOREIGN KEY (Maintenance_ID) REFERENCES HEBAS_Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_maint_ward FOREIGN KEY (Assigned_Ward) REFERENCES Wards(Ward_ID)
);

-- Single canonical Nurses definition
CREATE TABLE Nurses (
    Nurse_ID       NUMBER PRIMARY KEY,
    Shift_Timing   VARCHAR2(20),
    Assigned_Ward  NUMBER,
    CONSTRAINT fk_nurse_user FOREIGN KEY (Nurse_ID) REFERENCES HEBAS_Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_nurse_ward FOREIGN KEY (Assigned_Ward) REFERENCES Wards(Ward_ID)
);

CREATE TABLE Ambulance_Dispatcher (
    AD_ID           NUMBER PRIMARY KEY,
    Gender          VARCHAR2(10),
    Ambulance_Type  VARCHAR2(50),
    CONSTRAINT fk_ad_user FOREIGN KEY (AD_ID) REFERENCES HEBAS_Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Service_Dispatcher (
    SD_ID            NUMBER PRIMARY KEY,
    Service_Name     VARCHAR2(100),
    Contact_Radio    VARCHAR2(50),
    Shift_Timing     VARCHAR2(20),
    Assigned_Region  VARCHAR2(100),
    CONSTRAINT fk_sd_ad FOREIGN KEY (SD_ID) REFERENCES Ambulance_Dispatcher(AD_ID) ON DELETE CASCADE
);

CREATE TABLE Individual_Dispatcher (
    ID_ID       NUMBER PRIMARY KEY,
    Contact_No  VARCHAR2(15),
    Location    VARCHAR2(100),
    CONSTRAINT fk_id_ad FOREIGN KEY (ID_ID) REFERENCES Ambulance_Dispatcher(AD_ID) ON DELETE CASCADE
);

-- 8. WARD SPECIALIZATION
CREATE TABLE Burn_Wards (
    Ward_ID              NUMBER PRIMARY KEY,
    Sterilization_Level  VARCHAR2(20) CHECK (Sterilization_Level IN ('STANDARD', 'HIGH', 'MAXIMUM')),
    CONSTRAINT fk_burn_ward FOREIGN KEY (Ward_ID) REFERENCES Wards(Ward_ID) ON DELETE CASCADE
);

CREATE TABLE Trauma_Wards (
    Ward_ID                NUMBER PRIMARY KEY,
    Injury_Severity_Index  NUMBER CHECK (Injury_Severity_Index BETWEEN 1 AND 5),
    CONSTRAINT fk_trauma_ward FOREIGN KEY (Ward_ID) REFERENCES Wards(Ward_ID) ON DELETE CASCADE
);

CREATE TABLE Emergency_Room (
    Ward_ID                        NUMBER PRIMARY KEY,
    Priority_Level                 NUMBER,
    High_Concern_Patient_Capacity  NUMBER,
    Total_Staff                    NUMBER,
    CONSTRAINT fk_er_ward FOREIGN KEY (Ward_ID) REFERENCES Wards(Ward_ID) ON DELETE CASCADE
);

CREATE TABLE Recovery_Room (
    Ward_ID               NUMBER PRIMARY KEY,
    Recovery_Type         VARCHAR2(50),
    Is_Burn_Ward          NUMBER(1),
    Is_Trauma_Or_Medical  NUMBER(1),
    Is_Pediatrics         NUMBER(1),
    Total_Staff           NUMBER,
    CONSTRAINT fk_rr_ward FOREIGN KEY (Ward_ID) REFERENCES Wards(Ward_ID) ON DELETE CASCADE
);

CREATE TABLE Medical_Ward (
    Ward_ID                 NUMBER PRIMARY KEY,
    Chronic_Condition_Flag  NUMBER(1),
    CONSTRAINT fk_mw_rr FOREIGN KEY (Ward_ID) REFERENCES Recovery_Room(Ward_ID) ON DELETE CASCADE
);

CREATE TABLE Pediatric_Ward (
    Ward_ID                        NUMBER PRIMARY KEY,
    Parental_Accompaniment_Status  VARCHAR2(20),
    CONSTRAINT fk_pw_rr FOREIGN KEY (Ward_ID) REFERENCES Recovery_Room(Ward_ID) ON DELETE CASCADE
);

CREATE TABLE Ward_Manager (
    Ward_ID  NUMBER NOT NULL,
    UserID   NUMBER NOT NULL,
    Role     VARCHAR2(50),
    CONSTRAINT fk_wm_ward FOREIGN KEY (Ward_ID) REFERENCES Wards(Ward_ID),
    CONSTRAINT fk_wm_user FOREIGN KEY (UserID) REFERENCES HEBAS_Users(UserID)
);

-- 9. ALLOCATION / BRIDGE
CREATE TABLE Ward_Bed_Allocation (
    Allocation_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ward_ID        NUMBER NOT NULL,
    Bed_ID         NUMBER NOT NULL,
    Start_Time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    End_Time       TIMESTAMP,
    CONSTRAINT fk_wba_ward FOREIGN KEY (Ward_ID) REFERENCES Wards(Ward_ID),
    CONSTRAINT fk_wba_bed  FOREIGN KEY (Bed_ID)  REFERENCES Beds(Bed_ID)
);

CREATE TABLE Ward_Equipment (
    Ward_ID       NUMBER NOT NULL,
    Equipment_ID  NUMBER NOT NULL,
    Quantity      NUMBER DEFAULT 1,
    PRIMARY KEY (Ward_ID, Equipment_ID),
    CONSTRAINT fk_we_ward  FOREIGN KEY (Ward_ID)      REFERENCES Wards(Ward_ID),
    CONSTRAINT fk_we_equip FOREIGN KEY (Equipment_ID) REFERENCES Equipment(Equipment_ID)
);

-- 10. BED FEATURES
CREATE TABLE Bed_Feature (
    Feature_Name VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE Bed_Feature_Assignment (
    Bed_ID        NUMBER NOT NULL,
    Feature_Name  VARCHAR2(50) NOT NULL,
    PRIMARY KEY (Bed_ID, Feature_Name),
    CONSTRAINT fk_bfa_bed  FOREIGN KEY (Bed_ID)       REFERENCES Beds(Bed_ID),
    CONSTRAINT fk_bfa_feat FOREIGN KEY (Feature_Name) REFERENCES Bed_Feature(Feature_Name)
);

CREATE TABLE Bed_Buttons (
    Feature_Name  VARCHAR2(50) PRIMARY KEY,
    Button_Types  VARCHAR2(100),
    CONSTRAINT fk_bb_feat FOREIGN KEY (Feature_Name) REFERENCES Bed_Feature(Feature_Name)
);

CREATE TABLE Side_Table (
    Feature_Name         VARCHAR2(50) PRIMARY KEY,
    Side_Table_Category  VARCHAR2(50),
    CONSTRAINT fk_st_feat FOREIGN KEY (Feature_Name) REFERENCES Bed_Feature(Feature_Name)
);

CREATE TABLE Glucose_Strip (
    Feature_Name  VARCHAR2(50) PRIMARY KEY,
    Size_Strip    VARCHAR2(20),
    CONSTRAINT fk_gs_feat FOREIGN KEY (Feature_Name) REFERENCES Bed_Feature(Feature_Name)
);

CREATE TABLE BP_Machine (
    Feature_Name  VARCHAR2(50) PRIMARY KEY,
    BP_Category   VARCHAR2(50),
    CONSTRAINT fk_bpm_feat FOREIGN KEY (Feature_Name) REFERENCES Bed_Feature(Feature_Name)
);

-- 11. ADMISSIONS (dynamic clinical data; diagnosis columns inlined)
CREATE TABLE Admissions (
    Admission_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Patient_ID           NUMBER NOT NULL,
    Arrival_Timestamp    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Triage_Priority      NUMBER CHECK (Triage_Priority BETWEEN 1 AND 5),
    Chief_Complaint      VARCHAR2(255),
    Assigned_Doctor      NUMBER,
    Primary_Diagnosis    VARCHAR2(255),
    Diagnosis_Timestamp  TIMESTAMP,
    Discharge_Timestamp  TIMESTAMP,
    Admission_Status     VARCHAR2(20) DEFAULT 'ACTIVE',
    CONSTRAINT fk_adm_patient FOREIGN KEY (Patient_ID)      REFERENCES Patient_Profile(Patient_ID),
    CONSTRAINT fk_adm_doc     FOREIGN KEY (Assigned_Doctor) REFERENCES Doctor_Profiles(Doctor_ID)
);

-- 12. BED ASSIGNMENTS (transaction)
CREATE TABLE Bed_Assignments (
    Assignment_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID       NUMBER NOT NULL,
    Bed_ID             NUMBER NOT NULL,
    Assignment_Status  VARCHAR2(20) DEFAULT 'CURRENT',
    Start_Time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    End_Time           TIMESTAMP,
    CONSTRAINT fk_ba_adm FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID),
    CONSTRAINT fk_ba_bed FOREIGN KEY (Bed_ID)       REFERENCES Beds(Bed_ID)
);

-- 13. SANITIZATION LOGS (Equipment_Type inlined)
CREATE TABLE Sanitization_Logs (
    Sanitization_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Bed_ID           NUMBER NOT NULL,
    Maintenance_ID   NUMBER NOT NULL,
    Start_Timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    End_Timestamp    TIMESTAMP,
    Checking_Status  VARCHAR2(20) DEFAULT 'IN_PROGRESS',
    Equipment_Type   VARCHAR2(50),
    CONSTRAINT fk_san_bed   FOREIGN KEY (Bed_ID)         REFERENCES Beds(Bed_ID),
    CONSTRAINT fk_san_staff FOREIGN KEY (Maintenance_ID) REFERENCES Maintenance_Staff(Maintenance_ID)
);

-- 14. AUDIT + CONTACT
CREATE TABLE Audit_Trails (
    Audit_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Action_Type       VARCHAR2(20),
    Table_Name        VARCHAR2(50),
    Record_ID         NUMBER,
    Old_Value         VARCHAR2(255),
    New_Value         VARCHAR2(255),
    Action_Timestamp  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE User_Contact (
    UserID  NUMBER NOT NULL,
    Phone   VARCHAR2(15),
    CONSTRAINT fk_uc_user FOREIGN KEY (UserID) REFERENCES HEBAS_Users(UserID)
);

-- 15. OPERATIONAL / WORKFLOW
CREATE TABLE Hospitals (
    Hospital_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Hospital_Name   VARCHAR2(100) NOT NULL,
    Total_Beds      NUMBER,
    Occupied_Beds   NUMBER DEFAULT 0,
    Available_Beds  NUMBER DEFAULT 0
);

CREATE TABLE Arrival_Queue (
    Queue_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CNIC             VARCHAR2(15),
    Patient_Name     VARCHAR2(100),
    Chief_Complaint  VARCHAR2(100),
    Assigned_Ward    NUMBER,
    Assigned_Doctor  NUMBER,
    Arrival_Status   VARCHAR2(20)
);

CREATE TABLE Notifications (
    Notification_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_ID          NUMBER,
    Message          VARCHAR2(500),
    Status           VARCHAR2(20) DEFAULT 'UNREAD',
    Created_At       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Nurse_Assignments (
    Assignment_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nurse_ID       NUMBER,
    Admission_ID   NUMBER,
    Assigned_Date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_na_nurse FOREIGN KEY (Nurse_ID)     REFERENCES Nurses(Nurse_ID),
    CONSTRAINT fk_na_adm   FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID)
);

CREATE TABLE Medical_Measurements (
    Measurement_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID      NUMBER,
    BP_Value          VARCHAR2(20),
    Sugar_Value       NUMBER,
    Measurement_Date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mm_adm FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID)
);

CREATE TABLE Doctor_Assignment_History (
    History_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID     NUMBER,
    Doctor_ID        NUMBER,
    Assignment_Time  TIMESTAMP,
    CONSTRAINT fk_dah_adm FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID),
    CONSTRAINT fk_dah_doc FOREIGN KEY (Doctor_ID)    REFERENCES Doctor_Profiles(Doctor_ID)
);

CREATE TABLE Bed_Status_History (
    History_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Bed_ID      NUMBER,
    Old_Status  VARCHAR2(30),
    New_Status  VARCHAR2(30),
    Changed_At  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bsh_bed FOREIGN KEY (Bed_ID) REFERENCES Beds(Bed_ID)
);

CREATE TABLE Equipment_Inventory (
    Inventory_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Equipment_ID  NUMBER,
    Quantity      NUMBER,
    CONSTRAINT fk_ei_equip FOREIGN KEY (Equipment_ID) REFERENCES Equipment(Equipment_ID)
);

CREATE TABLE Patient_Transfers (
    Transfer_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID   NUMBER,
    From_Ward      NUMBER,
    To_Ward        NUMBER,
    Transfer_Time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pt_adm FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID)
);

CREATE TABLE Complaint_Mapping (
    Complaint_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Complaint_Name         VARCHAR2(100) UNIQUE,
    Recommended_Ward_ID    NUMBER,
    Recommended_Doctor_ID  NUMBER,
    CONSTRAINT fk_cm_ward FOREIGN KEY (Recommended_Ward_ID)   REFERENCES Wards(Ward_ID),
    CONSTRAINT fk_cm_doc  FOREIGN KEY (Recommended_Doctor_ID) REFERENCES Doctor_Profiles(Doctor_ID)
);

CREATE TABLE Nurse_Tasks (
    Task_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID   NUMBER,
    Nurse_ID       NUMBER,
    Task_Type      VARCHAR2(50),
    Task_Status    VARCHAR2(20) DEFAULT 'PENDING',
    Assigned_Time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nt_adm   FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID),
    CONSTRAINT fk_nt_nurse FOREIGN KEY (Nurse_ID)     REFERENCES Nurses(Nurse_ID)
);

CREATE TABLE Glucose_Strip_Results (
    Result_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID   NUMBER,
    Result_Status  VARCHAR2(20),
    Start_Time     TIMESTAMP,
    End_Time       TIMESTAMP,
    CONSTRAINT fk_gsr_adm FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID)
);

CREATE TABLE Patient_Vitals (
    Vital_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID  NUMBER,
    Nurse_ID      NUMBER,
    Systolic_BP   NUMBER,
    Diastolic_BP  NUMBER,
    Glucose_Level NUMBER,
    Temperature   NUMBER,
    Recorded_At   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pv_adm   FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID),
    CONSTRAINT fk_pv_nurse FOREIGN KEY (Nurse_ID)     REFERENCES Nurses(Nurse_ID)
);

CREATE TABLE Ambulance_Cases (
    Case_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Dispatcher_ID    NUMBER,
    Patient_Name     VARCHAR2(100),
    Pickup_Location  VARCHAR2(255),
    Complaint        VARCHAR2(255),
    Case_Status      VARCHAR2(30),
    CONSTRAINT fk_acase_disp FOREIGN KEY (Dispatcher_ID) REFERENCES Ambulance_Dispatcher(AD_ID)
);

CREATE TABLE Maintenance_Requests (
    Request_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Equipment_ID    NUMBER,
    Reported_By     NUMBER,
    Request_Status  VARCHAR2(20),
    CONSTRAINT fk_mr_equip FOREIGN KEY (Equipment_ID) REFERENCES Equipment(Equipment_ID),
    CONSTRAINT fk_mr_user  FOREIGN KEY (Reported_By)  REFERENCES HEBAS_Users(UserID)
);
