-- ============================================================================
-- HEBAS - 04_enhancements.sql
-- Production-completion objects. Additive only -- creates nothing that already
-- exists in 01/02/03. Safe to run on the live DB (idempotent index block) and
-- runs after 03 during a full rebuild (drop_all_objects clears these first).
-- Sections: Patient_Priority table, indexes, seed, functions, procedures,
--           package, views, triggers.
-- ============================================================================

-- ============== 1. PATIENT_PRIORITY ==============
CREATE TABLE Patient_Priority (
    Priority_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Admission_ID     NUMBER NOT NULL,
    Doctor_ID        NUMBER,
    Initial_Checkup  VARCHAR2(500),
    Priority_Level   NUMBER CHECK (Priority_Level BETWEEN 1 AND 5),
    Priority_Status  VARCHAR2(20) DEFAULT 'ACTIVE',
    Created_At       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pp_adm FOREIGN KEY (Admission_ID) REFERENCES Admissions(Admission_ID),
    CONSTRAINT fk_pp_doc FOREIGN KEY (Doctor_ID)    REFERENCES Doctor_Profiles(Doctor_ID)
);

-- ============== 2. INDEXES (idempotent: skips existing / already-indexed cols) ==============
BEGIN
    FOR s IN (
        SELECT 'IDX_ADM_PATIENT'        nm, 'Admissions(Patient_ID)'           col FROM dual UNION ALL
        SELECT 'IDX_ADM_DOCTOR',             'Admissions(Assigned_Doctor)'          FROM dual UNION ALL
        SELECT 'IDX_BA_ADMISSION',           'Bed_Assignments(Admission_ID)'        FROM dual UNION ALL
        SELECT 'IDX_BA_BED',                 'Bed_Assignments(Bed_ID)'              FROM dual UNION ALL
        SELECT 'IDX_PP_NATIONALID',          'Patient_Profile(National_ID)'         FROM dual UNION ALL
        SELECT 'IDX_CM_COMPLAINT',           'Complaint_Mapping(Complaint_Name)'    FROM dual UNION ALL
        SELECT 'IDX_NOTIF_USER',             'Notifications(User_ID)'               FROM dual UNION ALL
        SELECT 'IDX_PT_ADMISSION',           'Patient_Transfers(Admission_ID)'      FROM dual UNION ALL
        SELECT 'IDX_NA_NURSE',               'Nurse_Assignments(Nurse_ID)'          FROM dual UNION ALL
        SELECT 'IDX_AC_DISPATCHER',          'Ambulance_Cases(Dispatcher_ID)'       FROM dual UNION ALL
        SELECT 'IDX_PPR_ADMISSION',          'Patient_Priority(Admission_ID)'       FROM dual
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || s.nm || ' ON ' || s.col;
        EXCEPTION WHEN OTHERS THEN
            -- ORA-00955 name in use, ORA-01408 column list already indexed
            IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
        END;
    END LOOP;
END;
/

-- ============== 3. PATIENT_PRIORITY SEED ==============
INSERT INTO Patient_Priority (Admission_ID, Doctor_ID, Initial_Checkup, Priority_Level, Priority_Status)
VALUES (1, 2, 'Chest pain assessed; ECG and cardiac enzymes ordered.', 5, 'ACTIVE');
INSERT INTO Patient_Priority (Admission_ID, Doctor_ID, Initial_Checkup, Priority_Level, Priority_Status)
VALUES (2, 1, 'Compound femur fracture confirmed on X-ray; ortho consult.', 4, 'ACTIVE');
COMMIT;

-- ============== 4. FUNCTIONS ==============
CREATE OR REPLACE FUNCTION FN_GET_AVAILABLE_BEDS (p_ward_id IN NUMBER DEFAULT NULL)
RETURN NUMBER IS
    v_count NUMBER;
BEGIN
    IF p_ward_id IS NULL THEN
        SELECT COUNT(*) INTO v_count FROM Beds WHERE Current_Status = 'AVAILABLE';
    ELSE
        SELECT COUNT(*) INTO v_count
        FROM Beds b
        JOIN Ward_Bed_Allocation wba ON wba.Bed_ID = b.Bed_ID AND wba.End_Time IS NULL
        WHERE wba.Ward_ID = p_ward_id AND b.Current_Status = 'AVAILABLE';
    END IF;
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION FN_GET_WARD_OCCUPANCY (p_ward_id IN NUMBER)
RETURN NUMBER IS
    v_total NUMBER;
    v_occ   NUMBER;
BEGIN
    SELECT COUNT(*), NVL(SUM(CASE WHEN b.Current_Status = 'OCCUPIED' THEN 1 ELSE 0 END), 0)
    INTO v_total, v_occ
    FROM Beds b
    JOIN Ward_Bed_Allocation wba ON wba.Bed_ID = b.Bed_ID AND wba.End_Time IS NULL
    WHERE wba.Ward_ID = p_ward_id;
    IF v_total IS NULL OR v_total = 0 THEN RETURN 0; END IF;
    RETURN ROUND((v_occ / v_total) * 100, 1);
END;
/

CREATE OR REPLACE FUNCTION FN_GET_DOCTOR_WORKLOAD (p_doctor_id IN NUMBER)
RETURN NUMBER IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM Admissions
    WHERE Assigned_Doctor = p_doctor_id AND Admission_Status = 'ACTIVE';
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION FN_GET_NURSE_WORKLOAD (p_nurse_id IN NUMBER)
RETURN NUMBER IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM Admissions a
    JOIN Bed_Assignments ba ON ba.Admission_ID = a.Admission_ID AND ba.Assignment_Status = 'CURRENT'
    JOIN Ward_Bed_Allocation wba ON wba.Bed_ID = ba.Bed_ID AND wba.End_Time IS NULL
    JOIN Nurses n ON n.Assigned_Ward = wba.Ward_ID
    WHERE n.Nurse_ID = p_nurse_id AND a.Admission_Status = 'ACTIVE';
    RETURN v_count;
END;
/

CREATE OR REPLACE FUNCTION FN_GET_BED_STATUS (p_bed_id IN NUMBER)
RETURN VARCHAR2 IS
    v_status VARCHAR2(20);
BEGIN
    SELECT Current_Status INTO v_status FROM Beds WHERE Bed_ID = p_bed_id;
    RETURN v_status;
EXCEPTION WHEN NO_DATA_FOUND THEN
    RETURN NULL;
END;
/

-- ============== 5. PROCEDURES ==============
CREATE OR REPLACE PROCEDURE PR_CREATE_ADMISSION (
    p_patient_id   IN NUMBER,
    p_triage       IN NUMBER,
    p_complaint    IN VARCHAR2,
    p_admission_id OUT NUMBER
) AS
BEGIN
    INSERT INTO Admissions (Patient_ID, Triage_Priority, Chief_Complaint, Admission_Status)
    VALUES (p_patient_id, p_triage, p_complaint, 'ACTIVE')
    RETURNING Admission_ID INTO p_admission_id;
    BEGIN
        Auto_Assign_Doctor(p_admission_id);
    EXCEPTION WHEN OTHERS THEN NULL;  -- no complaint mapping: leave for manual triage
    END;
END;
/

CREATE OR REPLACE PROCEDURE PR_ASSIGN_DOCTOR (
    p_admission_id IN NUMBER,
    p_doctor_id    IN NUMBER
) AS
BEGIN
    -- Doctor_Assignment_History + doctor notification handled by triggers.
    UPDATE Admissions SET Assigned_Doctor = p_doctor_id WHERE Admission_ID = p_admission_id;
END;
/

CREATE OR REPLACE PROCEDURE PR_ASSIGN_BED (
    p_admission_id IN NUMBER,
    p_bed_id       IN NUMBER
) AS
BEGIN
    -- TRG_VALIDATE_BED_ASSIGNMENT + TRG_AUTO_OCCUPY_BED enforce rules / occupy.
    INSERT INTO Bed_Assignments (Admission_ID, Bed_ID, Assignment_Status)
    VALUES (p_admission_id, p_bed_id, 'CURRENT');
END;
/

CREATE OR REPLACE PROCEDURE PR_TRANSFER_PATIENT (
    p_admission_id IN NUMBER,
    p_to_ward      IN NUMBER
) AS
    v_bed       NUMBER;
    v_from_ward NUMBER := NULL;
    v_new_bed   NUMBER;
BEGIN
    BEGIN
        SELECT ba.Bed_ID INTO v_bed
        FROM Bed_Assignments ba
        WHERE ba.Admission_ID = p_admission_id AND ba.Assignment_Status = 'CURRENT';

        SELECT wba.Ward_ID INTO v_from_ward
        FROM Ward_Bed_Allocation wba
        WHERE wba.Bed_ID = v_bed AND wba.End_Time IS NULL;

        -- Release the current bed.
        UPDATE Bed_Assignments
        SET Assignment_Status = 'COMPLETED', End_Time = CURRENT_TIMESTAMP
        WHERE Admission_ID = p_admission_id AND Assignment_Status = 'CURRENT';
        UPDATE Beds SET Current_Status = 'PENDING_CLEANING' WHERE Bed_ID = v_bed;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        v_bed := NULL;  -- patient had no current bed
    END;

    INSERT INTO Patient_Transfers (Admission_ID, From_Ward, To_Ward)
    VALUES (p_admission_id, v_from_ward, p_to_ward);

    -- Place the patient in an available bed in the target ward, if any.
    BEGIN
        SELECT b.Bed_ID INTO v_new_bed
        FROM Beds b
        JOIN Ward_Bed_Allocation wba ON wba.Bed_ID = b.Bed_ID AND wba.End_Time IS NULL
        WHERE wba.Ward_ID = p_to_ward AND b.Current_Status = 'AVAILABLE'
        FETCH FIRST 1 ROWS ONLY;
        INSERT INTO Bed_Assignments (Admission_ID, Bed_ID, Assignment_Status)
        VALUES (p_admission_id, v_new_bed, 'CURRENT');
    EXCEPTION WHEN NO_DATA_FOUND THEN NULL;  -- no free bed in target ward
    END;
END;
/

CREATE OR REPLACE PROCEDURE PR_DISCHARGE_PATIENT (
    p_admission_id IN NUMBER
) AS
BEGIN
    -- TRG_AUTO_DISCHARGE_WORKFLOW frees bed + dispatches sanitization.
    UPDATE Admissions
    SET Discharge_Timestamp = CURRENT_TIMESTAMP, Admission_Status = 'DISCHARGED'
    WHERE Admission_ID = p_admission_id AND Admission_Status = 'ACTIVE';
END;
/

CREATE OR REPLACE PROCEDURE PR_ASSIGN_NURSE (
    p_nurse_id     IN NUMBER,
    p_admission_id IN NUMBER
) AS
BEGIN
    -- TRG_NOTIFY_NURSE notifies the nurse.
    INSERT INTO Nurse_Assignments (Nurse_ID, Admission_ID)
    VALUES (p_nurse_id, p_admission_id);
END;
/

CREATE OR REPLACE PROCEDURE PR_COMPLETE_SANITIZATION (
    p_sanitization_id IN NUMBER
) AS
    v_bed NUMBER;
BEGIN
    UPDATE Sanitization_Logs
    SET Checking_Status = 'COMPLETED', End_Timestamp = CURRENT_TIMESTAMP
    WHERE Sanitization_ID = p_sanitization_id AND Checking_Status <> 'COMPLETED'
    RETURNING Bed_ID INTO v_bed;

    IF v_bed IS NOT NULL THEN
        UPDATE Beds SET Current_Status = 'AVAILABLE'
        WHERE Bed_ID = v_bed AND Current_Status = 'PENDING_CLEANING';
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE PR_UPDATE_EQUIPMENT_STATUS (
    p_equipment_id IN NUMBER,
    p_status       IN VARCHAR2
) AS
BEGIN
    -- TRG_EQUIPMENT_AUDIT logs; TRG_MAINTENANCE_REQUEST opens a request if BROKEN.
    UPDATE Equipment SET Status = p_status WHERE Equipment_ID = p_equipment_id;
END;
/

CREATE OR REPLACE PROCEDURE PR_CREATE_AMBULANCE_CASE (
    p_dispatcher_id IN NUMBER,
    p_name          IN VARCHAR2,
    p_location      IN VARCHAR2,
    p_complaint     IN VARCHAR2,
    p_case_id       OUT NUMBER
) AS
BEGIN
    INSERT INTO Ambulance_Cases (Dispatcher_ID, Patient_Name, Pickup_Location, Complaint, Case_Status)
    VALUES (p_dispatcher_id, p_name, p_location, p_complaint, 'DISPATCHED')
    RETURNING Case_ID INTO p_case_id;
END;
/

CREATE OR REPLACE PROCEDURE PR_GENERATE_DAILY_REPORT AS
    v_total NUMBER;
    v_occ   NUMBER;
    v_avail NUMBER;
BEGIN
    SELECT COUNT(*),
           NVL(SUM(CASE WHEN Current_Status = 'OCCUPIED'  THEN 1 ELSE 0 END), 0),
           NVL(SUM(CASE WHEN Current_Status = 'AVAILABLE' THEN 1 ELSE 0 END), 0)
    INTO v_total, v_occ, v_avail
    FROM Beds;

    UPDATE Hospitals
    SET Total_Beds = v_total, Occupied_Beds = v_occ, Available_Beds = v_avail
    WHERE Hospital_ID = (SELECT MIN(Hospital_ID) FROM Hospitals);

    IF SQL%ROWCOUNT = 0 THEN
        INSERT INTO Hospitals (Hospital_Name, Total_Beds, Occupied_Beds, Available_Beds)
        VALUES ('HEBAS Central Hospital', v_total, v_occ, v_avail);
    END IF;
END;
/

-- ============== 6. PACKAGE ==============
CREATE OR REPLACE PACKAGE PKG_HEBAS AS
    PROCEDURE Assign_Bed       (p_admission_id NUMBER, p_bed_id NUMBER);
    PROCEDURE Assign_Doctor    (p_admission_id NUMBER, p_doctor_id NUMBER);
    PROCEDURE Transfer_Patient (p_admission_id NUMBER, p_to_ward NUMBER);
    PROCEDURE Discharge_Patient(p_admission_id NUMBER);
    PROCEDURE Assign_Nurse     (p_nurse_id NUMBER, p_admission_id NUMBER);
    PROCEDURE Generate_Report;
END PKG_HEBAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_HEBAS AS
    PROCEDURE Assign_Bed (p_admission_id NUMBER, p_bed_id NUMBER) IS
    BEGIN PR_ASSIGN_BED(p_admission_id, p_bed_id); END;

    PROCEDURE Assign_Doctor (p_admission_id NUMBER, p_doctor_id NUMBER) IS
    BEGIN PR_ASSIGN_DOCTOR(p_admission_id, p_doctor_id); END;

    PROCEDURE Transfer_Patient (p_admission_id NUMBER, p_to_ward NUMBER) IS
    BEGIN PR_TRANSFER_PATIENT(p_admission_id, p_to_ward); END;

    PROCEDURE Discharge_Patient (p_admission_id NUMBER) IS
    BEGIN PR_DISCHARGE_PATIENT(p_admission_id); END;

    PROCEDURE Assign_Nurse (p_nurse_id NUMBER, p_admission_id NUMBER) IS
    BEGIN PR_ASSIGN_NURSE(p_nurse_id, p_admission_id); END;

    PROCEDURE Generate_Report IS
    BEGIN PR_GENERATE_DAILY_REPORT; END;
END PKG_HEBAS;
/

-- ============== 7. VIEWS ==============
CREATE OR REPLACE VIEW VW_ACTIVE_ADMISSIONS AS
SELECT a.Admission_ID, a.Patient_ID, p.Full_Name, a.Triage_Priority, a.Chief_Complaint,
       a.Primary_Diagnosis, a.Assigned_Doctor, du.FName || ' ' || du.LName AS Doctor_Name,
       b.Bed_Number, a.Arrival_Timestamp
FROM Admissions a
JOIN Patient_Profile p ON p.Patient_ID = a.Patient_ID
LEFT JOIN HEBAS_Users du ON du.UserID = a.Assigned_Doctor
LEFT JOIN Bed_Assignments ba ON ba.Admission_ID = a.Admission_ID AND ba.Assignment_Status = 'CURRENT'
LEFT JOIN Beds b ON b.Bed_ID = ba.Bed_ID
WHERE a.Admission_Status = 'ACTIVE';

CREATE OR REPLACE VIEW VW_DOCTOR_WORKLOAD AS
SELECT d.Doctor_ID, u.FName || ' ' || u.LName AS Doctor_Name, d.Specialization, d.Department,
       COUNT(a.Admission_ID) AS Active_Patients
FROM Doctor_Profiles d
JOIN HEBAS_Users u ON u.UserID = d.Doctor_ID
LEFT JOIN Admissions a ON a.Assigned_Doctor = d.Doctor_ID AND a.Admission_Status = 'ACTIVE'
GROUP BY d.Doctor_ID, u.FName, u.LName, d.Specialization, d.Department;

CREATE OR REPLACE VIEW VW_NURSE_WORKLOAD AS
SELECT n.Nurse_ID, u.FName || ' ' || u.LName AS Nurse_Name, n.Assigned_Ward,
       (SELECT COUNT(*) FROM Admissions a
        JOIN Bed_Assignments ba ON ba.Admission_ID = a.Admission_ID AND ba.Assignment_Status = 'CURRENT'
        JOIN Ward_Bed_Allocation wba ON wba.Bed_ID = ba.Bed_ID AND wba.End_Time IS NULL
        WHERE wba.Ward_ID = n.Assigned_Ward AND a.Admission_Status = 'ACTIVE') AS Ward_Patients,
       (SELECT COUNT(*) FROM Nurse_Tasks t WHERE t.Nurse_ID = n.Nurse_ID AND t.Task_Status = 'PENDING') AS Pending_Tasks
FROM Nurses n
JOIN HEBAS_Users u ON u.UserID = n.Nurse_ID;

CREATE OR REPLACE VIEW VW_AVAILABLE_BEDS AS
SELECT b.Bed_ID, b.Bed_Number, b.Bed_Type, b.Bed_Size, wba.Ward_ID, w.Ward_Type
FROM Beds b
JOIN Ward_Bed_Allocation wba ON wba.Bed_ID = b.Bed_ID AND wba.End_Time IS NULL
JOIN Wards w ON w.Ward_ID = wba.Ward_ID
WHERE b.Current_Status = 'AVAILABLE';

CREATE OR REPLACE VIEW VW_OCCUPIED_BEDS AS
SELECT b.Bed_ID, b.Bed_Number, wba.Ward_ID, w.Ward_Type, a.Admission_ID, p.Full_Name
FROM Beds b
JOIN Ward_Bed_Allocation wba ON wba.Bed_ID = b.Bed_ID AND wba.End_Time IS NULL
JOIN Wards w ON w.Ward_ID = wba.Ward_ID
JOIN Bed_Assignments ba ON ba.Bed_ID = b.Bed_ID AND ba.Assignment_Status = 'CURRENT'
JOIN Admissions a ON a.Admission_ID = ba.Admission_ID
JOIN Patient_Profile p ON p.Patient_ID = a.Patient_ID
WHERE b.Current_Status = 'OCCUPIED';

CREATE OR REPLACE VIEW VW_PENDING_SANITIZATION AS
SELECT s.Sanitization_ID, s.Bed_ID, b.Bed_Number, s.Maintenance_ID,
       u.FName || ' ' || u.LName AS Staff_Name, s.Checking_Status,
       s.Start_Timestamp, s.Equipment_Type
FROM Sanitization_Logs s
JOIN Beds b ON b.Bed_ID = s.Bed_ID
LEFT JOIN HEBAS_Users u ON u.UserID = s.Maintenance_ID
WHERE s.Checking_Status <> 'COMPLETED';

CREATE OR REPLACE VIEW VW_EQUIPMENT_STATUS AS
SELECT Equipment_ID, Equipment_Name, Equipment_Type, Size_Area, Status FROM Equipment;

CREATE OR REPLACE VIEW VW_WARD_EQUIPMENT AS
SELECT we.Ward_ID, w.Ward_Type, e.Equipment_ID, e.Equipment_Name, we.Quantity, e.Status
FROM Ward_Equipment we
JOIN Wards w ON w.Ward_ID = we.Ward_ID
JOIN Equipment e ON e.Equipment_ID = we.Equipment_ID;

CREATE OR REPLACE VIEW VW_AMBULANCE_CASES AS
SELECT c.Case_ID, c.Patient_Name, c.Pickup_Location, c.Complaint, c.Case_Status,
       c.Dispatcher_ID, u.FName || ' ' || u.LName AS Dispatcher_Name
FROM Ambulance_Cases c
LEFT JOIN HEBAS_Users u ON u.UserID = c.Dispatcher_ID;

CREATE OR REPLACE VIEW VW_NOTIFICATIONS AS
SELECT n.Notification_ID, n.User_ID, u.FName || ' ' || u.LName AS User_Name,
       n.Message, n.Status, n.Created_At
FROM Notifications n
LEFT JOIN HEBAS_Users u ON u.UserID = n.User_ID;

-- ============== 8. TRIGGERS ==============
CREATE OR REPLACE TRIGGER TRG_UPDATE_WARD_CAPACITY
AFTER INSERT OR UPDATE OF Assignment_Status ON Bed_Assignments
FOR EACH ROW
DECLARE
    v_ward NUMBER;
BEGIN
    IF INSERTING AND :NEW.Assignment_Status = 'CURRENT' THEN
        BEGIN
            SELECT Ward_ID INTO v_ward FROM Ward_Bed_Allocation
            WHERE Bed_ID = :NEW.Bed_ID AND End_Time IS NULL;
            UPDATE Wards SET Current_Capacity = NVL(Current_Capacity, 0) + 1 WHERE Ward_ID = v_ward;
        EXCEPTION WHEN NO_DATA_FOUND THEN NULL; END;
    ELSIF UPDATING AND :OLD.Assignment_Status = 'CURRENT' AND :NEW.Assignment_Status <> 'CURRENT' THEN
        BEGIN
            SELECT Ward_ID INTO v_ward FROM Ward_Bed_Allocation
            WHERE Bed_ID = :NEW.Bed_ID AND End_Time IS NULL;
            UPDATE Wards SET Current_Capacity = GREATEST(NVL(Current_Capacity, 0) - 1, 0) WHERE Ward_ID = v_ward;
        EXCEPTION WHEN NO_DATA_FOUND THEN NULL; END;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BED_HISTORY
AFTER UPDATE OF Current_Status ON Beds
FOR EACH ROW
WHEN (NEW.Current_Status != OLD.Current_Status)
BEGIN
    INSERT INTO Bed_Status_History (Bed_ID, Old_Status, New_Status)
    VALUES (:NEW.Bed_ID, :OLD.Current_Status, :NEW.Current_Status);
END;
/

CREATE OR REPLACE TRIGGER TRG_DOCTOR_HISTORY
AFTER UPDATE OF Assigned_Doctor ON Admissions
FOR EACH ROW
WHEN (NEW.Assigned_Doctor IS NOT NULL AND (OLD.Assigned_Doctor IS NULL OR NEW.Assigned_Doctor != OLD.Assigned_Doctor))
BEGIN
    INSERT INTO Doctor_Assignment_History (Admission_ID, Doctor_ID, Assignment_Time)
    VALUES (:NEW.Admission_ID, :NEW.Assigned_Doctor, CURRENT_TIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_TRANSFER_HISTORY
AFTER INSERT ON Patient_Transfers
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Trails (Action_Type, Table_Name, Record_ID, Old_Value, New_Value)
    VALUES ('TRANSFER', 'Admissions', :NEW.Admission_ID,
            'Ward ' || :NEW.From_Ward, 'Ward ' || :NEW.To_Ward);
END;
/

CREATE OR REPLACE TRIGGER TRG_EQUIPMENT_AUDIT
AFTER UPDATE OF Status ON Equipment
FOR EACH ROW
WHEN (NEW.Status != OLD.Status)
BEGIN
    INSERT INTO Audit_Trails (Action_Type, Table_Name, Record_ID, Old_Value, New_Value)
    VALUES ('UPDATE', 'Equipment', :NEW.Equipment_ID, :OLD.Status, :NEW.Status);
END;
/

CREATE OR REPLACE TRIGGER TRG_ADMISSION_AUDIT
AFTER INSERT OR UPDATE OF Admission_Status ON Admissions
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO Audit_Trails (Action_Type, Table_Name, Record_ID, New_Value)
        VALUES ('INSERT', 'Admissions', :NEW.Admission_ID, :NEW.Admission_Status);
    ELSE
        INSERT INTO Audit_Trails (Action_Type, Table_Name, Record_ID, Old_Value, New_Value)
        VALUES ('UPDATE', 'Admissions', :NEW.Admission_ID, :OLD.Admission_Status, :NEW.Admission_Status);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_NOTIFY_DOCTOR
AFTER UPDATE OF Assigned_Doctor ON Admissions
FOR EACH ROW
WHEN (NEW.Assigned_Doctor IS NOT NULL AND (OLD.Assigned_Doctor IS NULL OR NEW.Assigned_Doctor != OLD.Assigned_Doctor))
BEGIN
    INSERT INTO Notifications (User_ID, Message)
    VALUES (:NEW.Assigned_Doctor, 'You have been assigned to admission #' || :NEW.Admission_ID || '.');
END;
/

CREATE OR REPLACE TRIGGER TRG_NOTIFY_NURSE
AFTER INSERT ON Nurse_Assignments
FOR EACH ROW
BEGIN
    INSERT INTO Notifications (User_ID, Message)
    VALUES (:NEW.Nurse_ID, 'You have been assigned to admission #' || :NEW.Admission_ID || '.');
END;
/

CREATE OR REPLACE TRIGGER TRG_AUTO_TRIAGE
BEFORE INSERT ON Admissions
FOR EACH ROW
WHEN (NEW.Triage_Priority IS NULL)
BEGIN
    IF :NEW.Chief_Complaint IS NULL THEN
        :NEW.Triage_Priority := 3;
    ELSIF UPPER(:NEW.Chief_Complaint) LIKE '%CHEST%'
       OR UPPER(:NEW.Chief_Complaint) LIKE '%STROKE%'
       OR UPPER(:NEW.Chief_Complaint) LIKE '%SHOCK%'
       OR UPPER(:NEW.Chief_Complaint) LIKE '%UNRESPONSIVE%'
       OR UPPER(:NEW.Chief_Complaint) LIKE '%BREATH%' THEN
        :NEW.Triage_Priority := 5;
    ELSIF UPPER(:NEW.Chief_Complaint) LIKE '%TRAUMA%'
       OR UPPER(:NEW.Chief_Complaint) LIKE '%FRACTURE%'
       OR UPPER(:NEW.Chief_Complaint) LIKE '%BLEED%' THEN
        :NEW.Triage_Priority := 4;
    ELSE
        :NEW.Triage_Priority := 2;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MAINTENANCE_REQUEST
AFTER UPDATE OF Status ON Equipment
FOR EACH ROW
WHEN (NEW.Status = 'BROKEN' AND OLD.Status != 'BROKEN')
BEGIN
    INSERT INTO Maintenance_Requests (Equipment_ID, Reported_By, Request_Status)
    VALUES (:NEW.Equipment_ID, NULL, 'OPEN');
END;
/
